### ISSUE TITLE
Font import is not working properly

### ISSUE THREAD

**Issue by jnoelg** [pebble/slate#4]
Environments: Windows Chrome (local files), Android Pebble Time App (web site hosted watchface config page).

Texts are rendered with a generic sans-serif font instead of the specific CSS defined fonts.

I was able to fix this issue by replacing the following lines:
```css
@import url(../fonts/pfdindisplaypro-regular.woff);
@import url(../fonts/ptsans-regular.woff);
```
by:
```css
@font-face {
  font-family: 'PF DinDisplay Pro';
  src: url('../fonts/pfdindisplaypro-regular.woff') format('woff');
}

@font-face {
  font-family: 'PT Sans';
  src: url('../fonts/ptsans-regular.woff') format('woff');
}
```
